final Map<String, String> gestureMap = {
  'straight_straight_straight_straight_straight': 'Bukas na Kamay',
  'fullybent_fullybent_fullybent_fullybent_fullybent': 'Saradong Kamay',
  'fullybent_straight_fullybent_fullybent_fullybent': 'Tignan mo',
  'fullybent_straight_straight_fullybent_fullybent': 'Kapayapaan',
  'fullybent_straight_fullybent_fullybent_straight': 'Napakahusay',
  'straight_fullybent_fullybent_fullybent_fullybent': 'Ayos',
  'fullybent_fullybent_straight_fullybent_fullybent': 'Masama',
  'straight_fullybent_fullybent_fullybent_straight': 'Tawag',
  'straight_straight_fullybent_fullybent_fullybent': 'Tama',  
  'straight_slightlybent_slightlybent_straight_straight': 'Masarap',
  'fullybent_fullybent_straight_straight_straight': 'Ako ay ayos lamang',
  'fullybent_fullybent_fullybent_fullybent_straight': 'Hinliliit',
  'slightlybent_slightlybent_slightlybent_slightlybent_slightlybent': 'Kalmadong Kamay',
};